package com.jetkollage.ui
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF416835)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFC1EFAF)
val onPrimaryContainerLight = Color(0xFF294F1F)
val secondaryLight = Color(0xFF8B4A62)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFD9E3)
val onSecondaryContainerLight = Color(0xFF6F334A)
val tertiaryLight = Color(0xFF37693D)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFB8F1B9)
val onTertiaryContainerLight = Color(0xFF1E5027)
val errorLight = Color(0xFF8F4A4B)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD9)
val onErrorContainerLight = Color(0xFF733335)
val backgroundLight = Color(0xFFF8FBF0)
val onBackgroundLight = Color(0xFF191D17)
val surfaceLight = Color(0xFFF5FAFB)
val onSurfaceLight = Color(0xFF171D1E)
val surfaceVariantLight = Color(0xFFDBE4E6)
val onSurfaceVariantLight = Color(0xFF3F484A)
val outlineLight = Color(0xFF6F797A)
val outlineVariantLight = Color(0xFFBFC8CA)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2B3133)
val inverseOnSurfaceLight = Color(0xFFECF2F3)
val inversePrimaryLight = Color(0xFFA6D395)
val surfaceDimLight = Color(0xFFD5DBDC)
val surfaceBrightLight = Color(0xFFF5FAFB)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFEFF5F6)
val surfaceContainerLight = Color(0xFFE9EFF0)
val surfaceContainerHighLight = Color(0xFFE3E9EA)
val surfaceContainerHighestLight = Color(0xFFDEE3E5)

val primaryDark = Color(0xFFA6D395)
val onPrimaryDark = Color(0xFF13380A)
val primaryContainerDark = Color(0xFF294F1F)
val onPrimaryContainerDark = Color(0xFFC1EFAF)
val secondaryDark = Color(0xFFFFB0CA)
val onSecondaryDark = Color(0xFF541D34)
val secondaryContainerDark = Color(0xFF6F334A)
val onSecondaryContainerDark = Color(0xFFFFD9E3)
val tertiaryDark = Color(0xFF9DD49E)
val onTertiaryDark = Color(0xFF023913)
val tertiaryContainerDark = Color(0xFF1E5027)
val onTertiaryContainerDark = Color(0xFFB8F1B9)
val errorDark = Color(0xFFFFB3B3)
val onErrorDark = Color(0xFF561D20)
val errorContainerDark = Color(0xFF733335)
val onErrorContainerDark = Color(0xFFFFDAD9)
val backgroundDark = Color(0xFF11140F)
val onBackgroundDark = Color(0xFFE1E4DA)
val surfaceDark = Color(0xFF0E1415)
val onSurfaceDark = Color(0xFFDEE3E5)
val surfaceVariantDark = Color(0xFF3F484A)
val onSurfaceVariantDark = Color(0xFFBFC8CA)
val outlineDark = Color(0xFF899294)
val outlineVariantDark = Color(0xFF3F484A)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDEE3E5)
val inverseOnSurfaceDark = Color(0xFF2B3133)
val inversePrimaryDark = Color(0xFF416835)
val surfaceDimDark = Color(0xFF0E1415)
val surfaceBrightDark = Color(0xFF343A3B)
val surfaceContainerLowestDark = Color(0xFF090F10)
val surfaceContainerLowDark = Color(0xFF171D1E)
val surfaceContainerDark = Color(0xFF1B2122)
val surfaceContainerHighDark = Color(0xFF252B2C)
val surfaceContainerHighestDark = Color(0xFF303637)







